### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by liuqi8827** [Steven-Ho/diayn-cont#1]
Thanks for your great work.

I'm facing a problem when I run **python main.py**

```
Traceback (most recent call last):
  File "/home/lq/diayn-cont/main.py", line 116, in <module>
    critic_1_loss, critic_2_loss, policy_loss, ent_loss, alpha = agent.update_parameters(memory, args.batch_size, updates)
  File "/home/lq/diayn-cont/sac.py", line 90, in update_parameters
    policy_loss.backward()
  File "/home/lq/anaconda3/envs/py3.6-DIAYN/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lq/anaconda3/envs/py3.6-DIAYN/lib/python3.6/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [256, 1]], which is output 0 of TBackward, is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Maybe we should add `.detach()` to a loss.**
Can you give me some suggestions?
Thanks a lot!

**Comment by Steven-Ho** [comment]
The problem is caused by PyTorch. Downgrade it to version 1.3.1
